name: MetaH
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.14
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - contourpy==1.2.1
      - matplotlib==3.8.4
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.13.0
      - six==1.16.0
      - tzdata==2024.1
